#variables to initialize the model to be parsed through

data_file: 'yeast_data/2021_INFERELATOR_DATA.h5ad'
gold_standard_file: 'yeast_data/YEASTRACT_20230601_BOTH.tsv.gz'

cvs: 5
epochs: 2
dropout: 0.2

ts: 1
sl: 30
n_dls: 2
tmin: 0
tmax: 60

use_prior: False
shuffle_prior: False

lr: 1e-3
wd: 1e-5
decay: False