cvs: 5
data_file: yeast_data/2021_INFERELATOR_DATA.h5ad
decay: false
dropout: 0.2
epochs: 500
gold_standard_file: yeast_data/YEASTRACT_20230601_BOTH.tsv.gz
lr: 0.001
n_dls: 3
output_file: mag_nODE_model/short_sl_experiments/sl20.yaml
shuffle_prior: false
sl: 20
tmax: 60
tmin: 0
ts: 1
use_prior: 'False'
wd: 1.0e-05
